services:
  agentes_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - reportsdb_data:/var/lib/postgresql/data
    networks:
      - report

  reports:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./pyproject.toml:/app/pyproject.toml
      - ./README.md:/app/README.md
    depends_on:
      - agentes_db
    restart: always
    networks:
      - report

volumes:
  reportsdb_data:

networks:
  report:
    driver: bridge
